// import Signature from "../../screens/App/Home/OrderReceive";

export const getImage = (name: string): any => {
    const images: Record<string, any>={
      dollar :require ('./dollar.png'),
      Frame:require('./Frame.png'),
      home:require('./home.png'),
      star:require('./star.png'),
      qrcode:require('./qrcode.png'),
      logistics:require('./logistics.png'),
      profile:require('./profile.png'),
      // bell: require('./bell.png'),
      // search:require('./search.png'),
     rank: require('./rank.png'),
     red:require('./red.png'),
     black:require('./black.png'),
     silver:require ('./silver.png'),
     arrow:require('./arrow.png'),
     tick:require('./tick.png'),
     tickk:require('./tickk.png'),
     gif:require('./gif.gif'),
     starone:require('./starone.png'),
     startwo:require("./startwo.png"),
     starthree:require('./starthree.png'),
     flash:require('./flash.png'),
     cross:require('./cross.png'),
     close:require('./close.png'),
     flag:require('./flag.png'),
     square:require('./square.png'),
     chart:require('./chart.png'),
     package:require('./package.png'),
     arrowdown:require('./arrowdown.png'),
     order:require('./order.png'),
     buttoncircle:require('./buttoncircle.png'),
     rightface:require('./rightface.png'),
     updown:require('./updown.png'),
     bag:require('./Logo/bag.png'),
     goldone:require('./Logo/goldone.png'),
     redone:require('./Logo/redone.png'),
     percent:require('./Logo/percent.png'),
     copy:require('./Logo/copy.png'),
     modallogo:require('./Logo/modallogo.png'),
     buttonlock:require('./Logo/buttonlock.png'),
     Silverlogo:require('./Logo/Silverlogo.png'),
     Goldlogo:require('./Logo/Goldlogo.png'),
     Platelogo:require('./Logo/Platelogo.png'),
     stack:require('./Logo/stack.png'),
     cash:require('./Logo/cash.png'),
     Code:require('./Logo/Code.png'),
     redeembox:require('./Logo/redeembox.png'),
     picone:require('./Logo/picone.png'),
     pictwo:require('./Logo/pictwo.png'),
     picthree:require('./Logo/picthree.png'),
     picfour:require('./Logo/picfour.png'),
     picfive:require('./Logo/picfive.png'),
     picsix:require('./Logo/picsix.png'),
     Animation:require('./Logo/Animation.png'),
     tablet:require('./Logo/tablet.png'),
     Text:require('./Scanner/Text.png'),
     signature:require('./Logo/signature.png'),

    };
    return images[name] || null;
};